using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace GuestbookWebApi.Model
{
    public class Guest
    {
        [BsonId]
        public ObjectId InternalId { get; set; }                // standard BSonId generated by MongoDb
        public string Id { get; set; }                          // external Id, easier to reference: 1,2,3 etc. 
        public string Name { get; set; } = string.Empty;
        public DateTime UpdatedOn { get; set; } = DateTime.Now;
        public DateTime CreatedOn { get; set; } = DateTime.Now;        
    }
}
